SELECT DISTINCT
  CASE 
    WHEN VEICULO.A009_in_status = 1 THEN 'ATIVO'
    ELSE 'BAIXADO'
  END AS STATUS_VEIC,
  STUFF(T882.A882_cod_sintetico, 1, 4, '') AS CC,
  VEICULO.A009_placa_veiculo AS PLACA,
  VEICULO.A009_quilomet_atual AS KM_ATUAL,
  T017.A017_nome_combustivel AS COMBUSTIVEL,
  T882.A882_dsc_cen_custo AS CLIENTE,
  A070_dscr_status AS DEPOSITO,
  T890.A890_dat_inicio AS DATA_ENTRADA_DO_CC,
  T890.A890_dat_final AS DATA_SAIDA__DO_CC,
  MOVIMENTACAO_VEICULO.A030_dt_inicio AS DATA_ENTRADA_NO_DEPOSITO,
  MOVIMENTACAO_VEICULO.A030_dt_final AS DATA_SAIDA_NO_DEPOSITO,
  MODE.A013_nome_modelo AS MODELO,
  FAB.A012_nome_fabricante AS MARCA,
  VEICULO.A009_ano_veiculo AS ANO_FAB,
  VEICULO.A009_ano_modelo AS ANO_MOD,
  T035.A035_dsc_cor AS COR,
  VEICULO.A009_dt_compra AS DATA_DE_COMPRA,
  VEICULO.A009_vl_compra AS VALOR_DA_COMPRA,
  VEICULO.A009_chassi AS CHASSI,
  VEICULO.A009_renavan AS RENAVAM,
  VEICULO.A009_uf_placa AS UF_DE_EMPLACAMENTO,
  T875.A875_nome_classificacao_frota AS TIPO_DE_VEICULO,
  VEICULO.A009_dt_pag_doc AS DATA_DA_NF,
  CASE 
    WHEN A070_dscr_status IN (
      '03 - CONTRATO', '04 - RESERVA', '05 - RESERVA ESPECÍFICA',
      '11 - MANUTENCAO', '19 - RETORNO DE LOCAÇÃO', '20 - LAVAGEM/ABASTEC',
      '25 - VEÍCULOS APREENDIDOS', '35 - DISPONÍVEL CONTRATO RAC'
    ) THEN 'ATIVA'
    ELSE 'NÃO ATIVA'
  END AS STATUS_ATIVIDADE;
